"""Structured final report. Pulls model outputs; marks human interpretation."""

from __future__ import annotations

from .case import CLIENT_NAME, PHILOSOPHY, TENSION_LINE, WINS_NOT_LAURA
from .provenance import utc_now


def build_report(ctx: dict) -> str:
    L = []
    p = L.append
    p(f"# Wharton Global High School Investment Competition — Research Report")
    p(f"Generated {utc_now()}")
    p(f"Client: {CLIENT_NAME}")
    p(f"Data mode: {ctx.get('data_mode', 'NO DATA')}")
    p("")
    p("## Executive Summary")
    p("[TEAM INPUT REQUIRED — write the story of the recommendation.]")
    p(f"Working model snapshot: {ctx.get('exec_snapshot', 'N/A')}")
    p("")
    p("## Client Understanding")
    p(WINS_NOT_LAURA)
    p("[TEAM INPUT REQUIRED — Laura's goals in your own words.]")
    p("")
    p("## Investment Problem")
    p("Fund ten fixed operating payments 2033–2042 with high confidence; then consider a responsible facility gift.")
    p("")
    p("## Objectives")
    p(ctx.get("objectives", "See IPS."))
    p("")
    p("## Constraints")
    p("WInS universe only. Virtual trades. Case payments not inflation-indexed (default).")
    p("")
    p("## Strategy")
    p(PHILOSOPHY)
    p(TENSION_LINE)
    p("")
    p("## Thesis Tension Framework")
    p("WHY own it, HOW LONG the reason lasts, WHY the market disagrees, WHAT would prove us wrong, HOW it behaves in scenarios, WHAT JOB it does for Laura, HOW risk changes into 2033.")
    p("")
    p("## Universe")
    p(ctx.get("universe_text", "N/A"))
    p("")
    p("## Screening")
    p(ctx.get("funnel_text", "N/A"))
    p("")
    p("## Research")
    p("[TEAM INPUT REQUIRED — interpret metrics; do not paste unexplained tables as research.]")
    p(ctx.get("research_text", ""))
    p("")
    p("## Key Investments")
    p(ctx.get("keep_text", "None marked INVEST/Keep yet."))
    p("")
    p("## Rejected Investments")
    p(ctx.get("reject_text", "No rejection log."))
    p("")
    p("## Portfolio")
    p(ctx.get("portfolio_text", "N/A"))
    p("")
    p("## Risk")
    p(ctx.get("risk_text", "N/A"))
    p("")
    p("## Scenario Analysis")
    p(ctx.get("scenario_text", "N/A"))
    p("")
    p("## Funding Analysis")
    p(ctx.get("funding_text", "N/A"))
    p("MODEL ESTIMATE — NOT PREDICTION. Does not include WInS simulation P&L.")
    p("")
    p("## 2033 Reserve")
    p(ctx.get("reserve_text", "N/A"))
    p("")
    p("## Facility Contribution Range")
    p(ctx.get("facility_text", "N/A"))
    p("[TEAM INPUT REQUIRED — the range is an input to discussion, not a gift recommendation.]")
    p("")
    p("## Trading Decisions")
    p(ctx.get("trades_text", "No virtual trades recorded."))
    p("")
    p("## Lessons Learned")
    p("[TEAM INPUT REQUIRED]")
    p(ctx.get("notes_text", ""))
    p("")
    p("## Conclusion")
    p("[TEAM INPUT REQUIRED]")
    return "\n".join(L)
